/* Custom: Fastlane Flexible — FastlaneCardComponent + own billing + 3DS (JSSDK & API flows) */
const { Router } = require('express')
const crypto = require('crypto')
const fetch = require('node-fetch')
const { getProduct, getProviderProducts } = require('../../../config/products')
const { getUSToken, getUSClientToken, API, getHeaders } = require('../../../config/paypal')
const C = require('../../../config/constants')

const router = Router()
const PROVIDER = 'paypal', SDK = 'jssdk-v5', KEY = 'fastlane-fp'

// In-memory session store: sessionKey → orderId (for API 3DS return flow, demo only)
// PayPal's card 3DS callback doesn't pass the orderId back in query params,
// so we embed a sessionKey in return_url before order creation and look it up here.
const threeDSSessionStore = new Map()

// camelCase (frontend) → PayPal snake_case shipping — copied from fastlane-pui (rule 1: no cross-product sharing)
function mapShipping(s) {
  if (!s || !s.address) return undefined
  const out = {
    type: 'SHIPPING',
    address: {
      address_line_1: s.address.addressLine1 || '',
      address_line_2: s.address.addressLine2 || '',
      admin_area_2:   s.address.adminArea2   || '',
      admin_area_1:   s.address.adminArea1   || '',
      postal_code:    s.address.postalCode   || '',
      country_code:   s.address.countryCode  || '',
    },
  }
  if (s.name && s.name.fullName) out.name = { full_name: s.name.fullName }
  if (s.phoneNumber && s.phoneNumber.countryCode && s.phoneNumber.nationalNumber) {
    out.phone_number = {
      country_code:    s.phoneNumber.countryCode,
      national_number: s.phoneNumber.nationalNumber,
    }
  }
  return out
}

// Builds order body for none/jssdk and API 3DS flows.
// sessionKey is pre-generated by the caller and embedded in return_url so the
// return handler can look up the orderId without relying on PayPal's callback params.
function buildFastlaneOrderBody({ amount, paymentToken, shippingAddress, threeDSFlow, req, sessionKey }) {
  const value = parseFloat(amount).toFixed(2) // USD, two decimal places
  const pu = {
    amount: {
      currency_code: 'USD',
      value,
      breakdown: { item_total: { currency_code: 'USD', value } },
    },
    description: C.DEMO_DESCRIPTION,
    items: [{ ...C.DEMO_ITEM, unit_amount: { currency_code: 'USD', value } }],
  }
  const shipping = mapShipping(shippingAddress)
  if (shipping) pu.shipping = shipping

  const card = { single_use_token: paymentToken.id }

  // API 3DS: inject verification + experience_context.
  // return_url carries ?session=<key> so we can look up orderId on return.
  if (threeDSFlow === 'api') {
    const origin = `${req.protocol}://${req.get('host')}`
    card.attributes = { verification: { method: 'SCA_ALWAYS' } }
    card.experience_context = {
      return_url: `${origin}/paypal/jssdk-v5/fastlane-fp/return?session=${sessionKey}`,
      cancel_url: `${origin}/paypal/jssdk-v5/fastlane-fp/return?fp_cancel=1`,
    }
  }

  return {
    intent: C.INTENT.CAPTURE,
    payment_source: { card },
    purchase_units: [pu],
  }
}

// GET /fastlane-fp — render demo page
router.get('/fastlane-fp', async (req, res) => {
  try {
    const product = getProduct(PROVIDER, SDK, KEY)
    const clientId = process.env.PAYPAL_US_CLIENT_ID
    const sdkClientToken = await getUSClientToken({ intent: 'sdk_init' })
    res.render('paypal/jssdk-v5/fastlane-fp', {
      title: product?.displayName ?? 'Fastlane Flexible',
      provider: PROVIDER, sdkVersion: SDK,
      currentProductKey: KEY, currentSdkVersion: SDK,
      sidebarProducts: getProviderProducts(PROVIDER),
      showSidebar: true,
      clientId,
      sdkClientToken,
      // three-domain-secure required for ThreeDomainSecureClient (unlike fastlane-pui)
      sdkUrl: `https://www.paypal.com/sdk/js?client-id=${clientId}&components=fastlane,three-domain-secure&buyer-country=US&currency=USD`,
      defaultAmount: req.query.amount || C.DEFAULT_AMOUNT,
      currency: 'USD',
    })
  } catch (err) {
    console.error('[fastlane-fp] render error:', err.message)
    res.status(500).send('Fastlane Flexible init failed: ' + err.message)
  }
})

// POST /api/fastlane-fp/create-order — create order (none / jssdk / api 3DS flow)
router.post('/api/fastlane-fp/create-order', async (req, res) => {
  try {
    const { paymentToken, shippingAddress, billingAddress, threeDSFlow } = req.body
    const amount = req.body.amount || C.DEFAULT_AMOUNT
    const flow = threeDSFlow || 'none'

    console.log('[fastlane-fp] create-order request body:', JSON.stringify({
      paymentTokenId: paymentToken && paymentToken.id,
      threeDSFlow: flow,
      amount,
      hasShipping: !!shippingAddress,
      hasBilling: !!billingAddress,
    }, null, 2))

    if (!paymentToken || !paymentToken.id) {
      return res.status(400).json({ error: 'paymentToken.id required' })
    }
    const amountErr = C.validateAmount(amount, 'USD')
    if (amountErr) return res.status(400).json({ error: amountErr })

    // Generate sessionKey before creating the order so it can be embedded in return_url.
    // PayPal's card 3DS callback doesn't include orderId in the redirect params,
    // so we store sessionKey→orderId after getting PayPal's response.
    const sessionKey = flow === 'api' ? crypto.randomBytes(16).toString('hex') : null

    const token = await getUSToken()
    const body = buildFastlaneOrderBody({ amount, paymentToken, shippingAddress, threeDSFlow: flow, req, sessionKey })

    console.log('[fastlane-fp] order body to PayPal:', JSON.stringify(body, null, 2))

    const r = await fetch(`${API}/v2/checkout/orders`, {
      method: 'POST',
      headers: getHeaders(token, { 'PayPal-Request-Id': Date.now().toString() }),
      body: JSON.stringify(body),
    })
    const order = await r.json()

    console.log('[fastlane-fp] create-order response:', JSON.stringify(order, null, 2))

    if (!r.ok) return res.status(r.status).json({ error: order.message, details: order })

    // Store sessionKey→orderId so return handler can look it up.
    // Auto-expire after 10 minutes in case buyer never returns.
    if (sessionKey && order.id) {
      threeDSSessionStore.set(sessionKey, order.id)
      setTimeout(() => threeDSSessionStore.delete(sessionKey), 10 * 60 * 1000)
    }

    res.json(order)
  } catch (err) {
    console.error('[fastlane-fp] create-order error:', err.message)
    res.status(500).json({ error: err.message })
  }
})

// GET /fastlane-fp/return — API 3DS callback: look up orderId via session, capture, render result.
// D1 decision: simple POST capture (known: refreshing this page shows ORDER_ALREADY_CAPTURED — expected).
router.get('/fastlane-fp/return', async (req, res) => {
  // inspect/probe: log all query params — PayPal sends state/code/liability_shift (not token/orderId)
  console.log('[fastlane-fp] return query params:', req.query)

  const commonVars = {
    title: 'Fastlane Flexible — Return',
    provider: PROVIDER, sdkVersion: SDK,
    currentProductKey: KEY, currentSdkVersion: SDK,
    sidebarProducts: getProviderProducts(PROVIDER),
    showSidebar: true,
    backUrl: '/paypal/jssdk-v5/fastlane-fp',
  }

  // Buyer cancelled on PayPal 3DS page
  if (req.query.fp_cancel) {
    return res.render('paypal/jssdk-v5/fastlane-fp-return', {
      ...commonVars, state: 'cancelled', captureId: null, orderJson: null,
    })
  }

  // Resolve orderId from session store (sessionKey was embedded in return_url before order creation)
  const sessionKey = req.query.session
  const orderId = sessionKey ? threeDSSessionStore.get(sessionKey) : null
  if (sessionKey) threeDSSessionStore.delete(sessionKey) // single-use: delete after reading

  console.log('[fastlane-fp] return — sessionKey:', sessionKey, '| orderId:', orderId)

  if (!orderId) {
    return res.render('paypal/jssdk-v5/fastlane-fp-return', {
      ...commonVars,
      state: 'error', captureId: null,
      orderJson: JSON.stringify({
        error: 'Order ID not found — session may have expired (>10 min), already been used, or return_url mismatch',
        query: req.query,
      }, null, 2),
    })
  }

  try {
    const token = await getUSToken()
    const r = await fetch(`${API}/v2/checkout/orders/${orderId}/capture`, {
      method: 'POST',
      headers: getHeaders(token, { 'PayPal-Request-Id': Date.now().toString() }),
    })
    const order = await r.json()

    console.log('[fastlane-fp] return capture response:', JSON.stringify(order, null, 2))

    // Rule 13: must check captures[0].status === 'COMPLETED'
    const capture = order.purchase_units &&
      order.purchase_units[0] &&
      order.purchase_units[0].payments &&
      order.purchase_units[0].payments.captures &&
      order.purchase_units[0].payments.captures[0]

    const ok = !!(capture && capture.status === 'COMPLETED')
    res.render('paypal/jssdk-v5/fastlane-fp-return', {
      ...commonVars,
      state: ok ? 'success' : 'error',
      captureId: ok ? capture.id : null,
      orderJson: JSON.stringify(order, null, 2),
    })
  } catch (err) {
    console.error('[fastlane-fp] return capture error:', err.message)
    res.render('paypal/jssdk-v5/fastlane-fp-return', {
      ...commonVars,
      state: 'error', captureId: null,
      orderJson: JSON.stringify({ error: err.message }, null, 2),
    })
  }
})

module.exports = router
